name: Manual Update Server

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Server to set as active'
        required: true
        type: choice
        options:
          - 'zimbor.go.ro'
          - 'peviitor.go.ro'
          - 'zimbor.go.ro:8985'
          - 'srvalx.duckdns.org:8983'
        default: 'zimbor.go.ro'

jobs:
  manual-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update Configuration File Manually
      run: |
        CONFIG_FILE="v3/config.php"
        BACKUP_FILE="$CONFIG_FILE.bak"
        manual_server="${{ github.event.inputs.server }}"

        # Backup the original config file
        cp $CONFIG_FILE $BACKUP_FILE

        # Escape single quotes and other special characters in the server name
        escaped_manual_server=$(echo "$manual_server" | sed "s/[']/\\\\'/g")

        # Comment out all existing server lines
        sed -i -e 's/^\s*\$server = /\/\/\$server = /' $CONFIG_FILE

        # Uncomment the line for the manual server
        sed -i "s/\/\/\$server = '$manual_server';/\$server = '$manual_server';/" $CONFIG_FILE

        # Check if the configuration file has been updated
        if ! cmp -s $CONFIG_FILE $BACKUP_FILE; then
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add $CONFIG_FILE
          git commit -m "Manually updated server to $manual_server"
          git push
        else
          echo "No changes made to the config file."
        fi
